### PR TITLE
#setup Import moralis SDK and modify setup scene

### PR DESCRIPTION
**Pull request by Michae-zHOU**

### CODE REVIEW

**Comment by Michae-zHOU** [comment]
@brandon-liu-git gentle ping on review

**Review by brandon-liu-git — COMMENTED** [review]
Sorry for my late reply. It looks like a huge commit. My browser has broken several times. Is it for project setup? Any functions included in this PR?

**Comment by Michae-zHOU** [comment]
> Sorry for my late reply. It looks like a huge commit. My browser has broken several times. Is it for project setup? Any functions included in this PR? 

It's a simple UI allows user to connect metamask. You can try it out on your end.

**Comment by Michae-zHOU** [comment]
Lets just approve quicker and get clarification next time. Don't block any PR for more than one day.

**Review by brandon-liu-git — APPROVED** [review]
Can you include some instructions here so that we can try on our local machine?

**Comment by Michae-zHOU** [comment]
> 

You can sync the code and open the project in Unity.

**Comment by Michae-zHOU** [comment]
It only has a button in the UI. After you click the button, you will be able to scan a QR code and read the balance of your wallet.

**Comment by brandon-liu-git** [comment]
> > 
> 
> You can sync the code and open the project in Unity.

sounds good. LGTM.

**Comment by Michae-zHOU** [comment]
For Unity Game Project, it usually puts all the game scenes and logic into Asset Folder.

Package is the imported library. Feel free to check out this page. https://unity.com/how-to/organizing-your-project

**Pull request merged**
